apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: kafka-cluster   # 填写所属 kafka 集群名称
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 7200000    # 保留在 topic 中的保留期，
    segment.bytes: 1073741824  # 日志的文件大小